### ISSUE TITLE
Crash when using the "Implement pure virtual functions" Quick Action

### ISSUE THREAD

**Issue by JordanTHarris** [thennequin/VS-QuickNavigation#1]
First off, I'd like to say that this is a really nice extension and is something I've been wanting in Visual Studio for a while. The fuzzy searching works just as I'd expect. I need a feature similar to this for my C++ app and I'll probably try and learn from this if I can.

Anyways, I'm getting a crash when using the "<b>Implement pure virtual functions for base</b>" feature in <i>Quick Actions</i>. This is in Visual C++, by the way. I'm not sure why this would affect that, but I tested it was this extension by disabling it to see if the crash still happened.

**Comment by thennequin** [comment]
@JordanTHarris Hi Jordan, thanks.
The code is open, go ahead. :)

I don't understand how do you get this crash.
What version of Visual Studio are you using?
And how can I reproduce this crash exactly?
Thank you in advance for your answer.

**Comment by JordanTHarris** [comment]
I can't seem to reproduce this crash anymore. Maybe disabling it and re-enabling it made it work again. I really don't know. I think you're good though. :)  I'll let you know if I ever have this problem again though.

**Comment by JordanTHarris** [comment]
I can't seem to reproduce this crash anymore. Maybe disabling it and re-enabling it made it work again. I really don't know. I think you're good though. :)  I'll let you know if I ever have this problem again though. It was with VS2015 though.

**Comment by JordanTHarris** [comment]
I can't seem to reproduce this crash anymore. Maybe disabling it and re-enabling it made it work again. I really don't know. I think you're good. :) I'll let you know if I ever have this problem again though. It was with VS2015.

**Comment by thennequin** [comment]
Ok, maybe next time.
